apiVersion: v1
kind: Namespace
metadata:
  name: production

---
apiVersion: v1
kind: Service
metadata:
  name: topsong
  namespace: production
  labels:
    app: topsong
spec:
  selector:
    app: topsong
  ports:
  - port: 80
    name: http
    targetPort: 3000
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: topsong
  namespace: production
spec:
  selector:
    matchLabels:
      app: topsong
  strategy:
    type: RollingUpdate
  template: #Template for container
    metadata:
      labels:
        app: topsong
    spec:
      containers:
      - name: topsong
        image:  asia.gcr.io/$PROJECT_ID/production/topsong:$SHORT_SHA
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          name: topsong
        resources:
          requests:
            cpu: 50m

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: topsong
  namespace: production
  annotations:
    kubernetes.io/ingress.global-static-ip-name: spotifyapi-1
    kubernetes.io/ingress.allow-http: "true"
    networking.gke.io/managed-certificates: 
spec:
  rules:
    - host: 
      http:
        paths:
        - path: /*
          pathType: ImplementationSpecific
          backend:
            service:
              name: topsong
              port: 
                number: 80

