apiVersion: apps/v1
kind: Deployment
metadata:
  name: topsong
spec:
  replicas: 1
  selector:
    matchLabels:
      app: topsong
  template:
    metadata:
      labels:
        app: topsong
    spec:
      containers:
      - name: topsong
        image: song-api:latest
        ports:
        - containerPort: 3000
