apiVersion: apps/v1
kind: Deployment
metadata:
  name: song-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: song-api
  template:
    metadata:
      labels:
        app: song-api
    spec:
      containers:
      - name: song-api
        image: song-api:latest
        ports:
        - containerPort: 3000
