apiVersion: batch/v1
kind: Job
metadata:
  name: load-data-job
spec:
  template:
    spec:
      containers:
      - name: load-data-container
        image: gcr.io/bfitask-k8s/load-data:latest  
        command: ["python", "load_data.py"]
      restartPolicy: Never
