apiVersion: batch/v1
kind: Job
metadata:
  name: load-data-job
spec:
  template:
    metadata:
      name: topsong
    spec:
      containers:
      - name: load-data-container
        image: asia.gcr.io/bfi-task/load_data:latest  # Replace with your load_data.py image name from GCR
        command: ["python", "load_data.py"]
      restartPolicy: Never
